// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomestico"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("9b74566b-60f5-4e63-939a-a09c0037c1e8"),
                            Category = 1,
                            Description = "Lavarropa automatico Drean Next 6.06 Eco, 6kl, Blanco",
                            Discount = 20,
                            ImageUrl = "https://megatonedigital.vteximg.com.br/arquivos/ids/156425-520-520/135728_01.jpg?v=638265420231900000",
                            Name = "Lavarropa Drean",
                            Price = 740299m
                        },
                        new
                        {
                            ProductId = new Guid("c78611d9-f83f-43fd-bc68-f58947c27c04"),
                            Category = 1,
                            Description = "Microonda Daewoo, 23 Litros Bifunción D223dg",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/32/MKT0005BGH-1.jpg",
                            Name = "Microonda Daewoo ",
                            Price = 400846m
                        },
                        new
                        {
                            ProductId = new Guid("73a515cb-2f77-41e2-8604-78392ac915df"),
                            Category = 1,
                            Description = "Heladera Conqueror, 329L 2F-1600bda ",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/35/HEL1688CNQ.jpg",
                            Name = "Heladera Conqueror",
                            Price = 732299m
                        },
                        new
                        {
                            ProductId = new Guid("ebca9848-782e-407f-9f8f-9d88c8b6a8e7"),
                            Category = 1,
                            Description = " Cocina Florencia 5518F Inoxidable Multigas Con 4 Hornallas",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/31/COC5518FLO.jpg",
                            Name = "Cocina Florencia",
                            Price = 519399m
                        },
                        new
                        {
                            ProductId = new Guid("d05af8ee-97ac-46b1-bf22-6fb269bfec22"),
                            Category = 2,
                            Description = "Celular Liberado A34 Gris 128 Gb, Ram 6 Gb, Octa Core",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/209/02/KIT3463SSG.jpg",
                            Name = "Celular Sansung A34",
                            Price = 695999m
                        },
                        new
                        {
                            ProductId = new Guid("d67e9c3f-2306-4ba2-904b-6dc2538bdcd6"),
                            Category = 2,
                            Description = "Notebook Cel Fire Glw2, Ram 4G, SSD 128 Gb, Pantalla 14",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/200/04/NOT2128PCB.jpg",
                            Name = "Notebook PCBOX",
                            Price = 499999m
                        },
                        new
                        {
                            ProductId = new Guid("ec8422ac-374c-47f8-902d-3e0a79c9c7ee"),
                            Category = 2,
                            Description = "Joystick Robot Con Conexión Inalámbrica, Microsoft",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/235/JOY6910MIC.jpg",
                            Name = "Joystick Xbox",
                            Price = 129999m
                        },
                        new
                        {
                            ProductId = new Guid("9e2b0162-b233-46e9-9fe0-b268495efb77"),
                            Category = 2,
                            Description = "Tablet Wave 7 Dual I726a10, 2Gb, Ram 16Gb, Wifi",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/224/MKT0054EXO-1.jpg",
                            Name = "Tablet Wave 7 Exo",
                            Price = 134999m
                        },
                        new
                        {
                            ProductId = new Guid("c2e71e36-090d-4853-b118-2e782f253ce2"),
                            Category = 3,
                            Description = "Reloj Inteligente, Negro, Bluetooth, Android, Notificaciones, Resistente al agua",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/239/MKT0034DXE.jpg",
                            Name = "Reloj Smartwatch Nt04",
                            Price = 33798m
                        },
                        new
                        {
                            ProductId = new Guid("345fe562-4ffa-41df-8118-088182eb14b1"),
                            Category = 3,
                            Description = "Anteojos de sol, Negro mate, lente gris ",
                            Discount = 0,
                            ImageUrl = "https://infinit.la/cdn/shop/products/6_f14d1e1f-e535-42e0-84ce-07c9f0aa93eb.jpg?v=1681141624&width=800",
                            Name = "Lentes de Sol Exclamation",
                            Price = 129000m
                        },
                        new
                        {
                            ProductId = new Guid("80648e78-49e9-482c-aa57-ae707b613023"),
                            Category = 3,
                            Description = "Zapatillas de running, color negro, talle 44",
                            Discount = 0,
                            ImageUrl = "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/2881496d3d514a33905ef338f92dc37d_9366/zapatillas-de-running-adizero-sl.jpg",
                            Name = "Zapatillas Adizero Adidas",
                            Price = 171999m
                        },
                        new
                        {
                            ProductId = new Guid("942431e4-48e5-41ea-9ef5-706fd1cd0ed5"),
                            Category = 3,
                            Description = "Riñonera Adicolor Classic",
                            Discount = 0,
                            ImageUrl = "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/5460d79ff58c46dcac93ae6701128b5e_9366/rinonera-adicolor-classic.jpg",
                            Name = "Riñonera Adicolor Adidas",
                            Price = 35999m
                        },
                        new
                        {
                            ProductId = new Guid("2c53350d-6ee7-4445-9137-019715d7a1eb"),
                            Category = 4,
                            Description = "Colchón 1 Plaza Resorte Bonnell Babel 0.80 X 1.90",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom/140/CHO7062IDL.jpg?version=35",
                            Name = "Colchón Bonnell Babel Inducol",
                            Price = 216999m
                        },
                        new
                        {
                            ProductId = new Guid("8d33b667-9445-42f6-b0de-0f194434daba"),
                            Category = 4,
                            Description = "Sillón De 3 Cuerpos, Esquinero,1.85Mts, Chenille Gris ",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/270/MKT0022AWO.jpg",
                            Name = "Sillón American Wood",
                            Price = 600000m
                        },
                        new
                        {
                            ProductId = new Guid("0653e07c-b3b1-433e-b473-a01c00874d7e"),
                            Category = 4,
                            Description = "Divan Cama Pacifico, Madera, Ancho 90 Cm, largo 204 Cm",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/273/DIV0001INM.jpg",
                            Name = "Divan Inmacol",
                            Price = 259000m
                        },
                        new
                        {
                            ProductId = new Guid("faaa3eee-4d88-4662-a1df-6bab00812a5e"),
                            Category = 4,
                            Description = "Silla Comedor, Nórdica Eames, Diseño Moderno, Color Verde",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/339/MKT0250VIV.jpg",
                            Name = "Silla Comedor Vita Meet Makom",
                            Price = 179000m
                        },
                        new
                        {
                            ProductId = new Guid("cb28c377-70e5-4adb-b66c-6d851f57b05b"),
                            Category = 5,
                            Description = "Lavable Con Agua, Recargable, Color Negro",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom/76/AFE2724PHI.jpg?version=35",
                            Name = "Afeitadora Oneblade Qp2724, Philips",
                            Price = 52999m
                        },
                        new
                        {
                            ProductId = new Guid("c08b5aab-3b83-4e65-8fbc-71c80f6ad9f0"),
                            Category = 5,
                            Description = "Uso En Humedo, No recargable, Potencia Total 2400 ",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/articulos/zoom2x/97/SEC0215GAM.jpg",
                            Name = "Secador De Pelo Eleganza Gama",
                            Price = 84800m
                        },
                        new
                        {
                            ProductId = new Guid("acdc4528-9ddf-4852-a629-2affb5be62dc"),
                            Category = 5,
                            Description = "Planchita de pelo, No recargable, Potencia Total 2400 ",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/97/PLA2118GAM.jpg",
                            Name = "Plancha Elegance Gamma",
                            Price = 101000m
                        },
                        new
                        {
                            ProductId = new Guid("25fda333-7589-40b5-a764-b6aea9e2b320"),
                            Category = 5,
                            Description = "Balanza Digital Vidrio Templado Hasta 150Kg",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/78/MKT0132PHO-1.jpg",
                            Name = "Balanza Digital Atma Ba7504n",
                            Price = 23400m
                        },
                        new
                        {
                            ProductId = new Guid("7cb16dfc-c3e3-4037-8e0e-4f7bfed7bfe1"),
                            Category = 6,
                            Description = "Con regulador, Visera, Color Azul",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/232/CAS0033SLP.jpg",
                            Name = "Casco Ciclismo Wt-032",
                            Price = 27600m
                        },
                        new
                        {
                            ProductId = new Guid("62652dd1-26a7-4a3b-af77-98fc8bc1ec6e"),
                            Category = 6,
                            Description = "Rodado 29, Talle 18, Color Blanco",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/104/BIC2920NRD.jpg",
                            Name = "Bicicleta Mountain Bike Nordic",
                            Price = 320000m
                        },
                        new
                        {
                            ProductId = new Guid("dd16d78d-2de9-4c7b-984d-76ad05abdf40"),
                            Category = 6,
                            Description = "Velocidad 12 Km/h, Peso Máximo Soportado 100 kl",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/111/MKT0650ATR-1.jpg",
                            Name = "Cinta Caminadora Randers Arg-407",
                            Price = 716519m
                        },
                        new
                        {
                            ProductId = new Guid("24f5e33f-de5a-40e4-87b4-98d779e32135"),
                            Category = 6,
                            Description = "Rodado 26, Con 7 Velocidades,Talle 18, Color Azul",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/104/MKT0379DNC-1.jpg",
                            Name = "Bicicleta De Paseo Lamborghini",
                            Price = 350490m
                        },
                        new
                        {
                            ProductId = new Guid("418b2c87-ce2a-49ad-80fa-e53fb3adfe13"),
                            Category = 7,
                            Description = "Con Lentejuelas Reversibles y Protecciones, Talle 36",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/257/MKT0104DNC.jpg",
                            Name = "Patines Lamborghini",
                            Price = 98020m
                        },
                        new
                        {
                            ProductId = new Guid("703072b3-4440-4e26-bf8f-8b3230ceae8b"),
                            Category = 7,
                            Description = "Silla de comer, Color rosa",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/119/MKT0203DNC.jpg",
                            Name = "Sillita De Comer Booster Lamborghini",
                            Price = 97860m
                        },
                        new
                        {
                            ProductId = new Guid("19f7128a-f6bc-4adf-be23-f505dbb7c5b9"),
                            Category = 7,
                            Description = "Caminador musical con panel didactico",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/325/MKT0616ATR-1.jpg",
                            Name = "Caminador Musical Bebesit 1226",
                            Price = 52280m
                        },
                        new
                        {
                            ProductId = new Guid("b61b5a8c-c75f-4e2c-b642-0806d49276dc"),
                            Category = 7,
                            Description = "Moto a batería, Color azul y negro",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/362/MKT0032BBS-1.jpg",
                            Name = "Moto a batería Bmw K1300",
                            Price = 530000m
                        },
                        new
                        {
                            ProductId = new Guid("470e7424-0f8c-4fb3-b5ac-5f5b8ac37776"),
                            Category = 8,
                            Description = "Gaseosa 500 ml",
                            Discount = 0,
                            ImageUrl = "https://cdn.tiendanegocio.com/gallery/17745/img_17745_18b20896ea8.jpeg",
                            Name = "Coca Cola 500 ml",
                            Price = 750m
                        },
                        new
                        {
                            ProductId = new Guid("9ede373f-ebeb-48c0-9aef-fb9cb9f3313f"),
                            Category = 8,
                            Description = "Vino malbec 750 ml",
                            Discount = 0,
                            ImageUrl = "https://cdn.tiendanegocio.com/gallery/17745/img_17745_18b4b8c013b.jpeg",
                            Name = "Dv Catena Malbec",
                            Price = 15800m
                        },
                        new
                        {
                            ProductId = new Guid("0750083e-dabd-4c5f-9995-c454ad711bb1"),
                            Category = 8,
                            Description = "Cafe torrado, 170 GR",
                            Discount = 0,
                            ImageUrl = "https://cdn.tiendanegocio.com/gallery/17745/img_17745_18b1f7b2bf9.jpeg",
                            Name = "Cafe Dolca",
                            Price = 1900m
                        },
                        new
                        {
                            ProductId = new Guid("0ac8c8a4-fa71-4f7b-825c-aed4e78e63cb"),
                            Category = 8,
                            Description = "Ferrero x140g",
                            Discount = 0,
                            ImageUrl = "https://www.golomax.com.ar/uploads/centum/articles/home/7003428_1.jpg",
                            Name = "Nutella",
                            Price = 2565m
                        },
                        new
                        {
                            ProductId = new Guid("c4834922-c7f6-4eee-a8c7-00d422ceddd9"),
                            Category = 9,
                            Description = "Autor Dibu Martinez, Libro tapa blanda",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/2733557-thickbox_default/dibu-martinez-pasion-por-el-futbol.jpg",
                            Name = "Pasión por el fútbol",
                            Price = 12800m
                        },
                        new
                        {
                            ProductId = new Guid("ab66afba-77da-4bba-adea-8b5496605fad"),
                            Category = 9,
                            Description = "Autor Michael Crichton, Libro tipo bolsillo",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/3243614-thickbox_default/parque-jurasico-jurassic-park.jpg",
                            Name = "Parque Jurásico",
                            Price = 23500m
                        },
                        new
                        {
                            ProductId = new Guid("29a21ee2-535b-4750-87af-6a85b413a287"),
                            Category = 9,
                            Description = "Autor Rick Riordan, Libro tapa blanda",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/3477641-thickbox_default/la-torre-de-neron-las-pruebas-de-apolo-5.jpg",
                            Name = "La torre de Nerón, Las pruebas de Apolo 5",
                            Price = 29900m
                        },
                        new
                        {
                            ProductId = new Guid("e792cffb-1561-4ea7-99a5-58f7df27b777"),
                            Category = 9,
                            Description = "Autor Ernest Cline, Libro tapa blanda",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/3495318-thickbox_default/ready-player-two.jpg",
                            Name = "Ready player Two",
                            Price = 30800m
                        },
                        new
                        {
                            ProductId = new Guid("43386dc5-62ec-451c-9b18-4b2c26481a83"),
                            Category = 10,
                            Description = "Material madera",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/343/MKT0425EMC-1.jpg",
                            Name = "Reposera para jardín EMC",
                            Price = 246800m
                        },
                        new
                        {
                            ProductId = new Guid("2f8fc42b-0e05-4e56-8327-28fe3c59f1e2"),
                            Category = 10,
                            Description = "Material madera",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/343/MKT0425EMC-1.jpg",
                            Name = "Reposera para jardín EMC",
                            Price = 246800m
                        },
                        new
                        {
                            ProductId = new Guid("90c352bb-3edb-40e2-9a18-a0e80593420f"),
                            Category = 10,
                            Description = "Parrilla portátil, plegable para camping",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/316/MKT0048IUR.jpg",
                            Name = "Parrilla portátil carbón balcon Mor Amazonas",
                            Price = 64900m
                        },
                        new
                        {
                            ProductId = new Guid("c59aebb8-d715-47b0-8583-ed510c135b75"),
                            Category = 10,
                            Description = "Gazebo de 6X3, con puerta y ventanas, Color blanco",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/114/MKT0058RBJ.jpg",
                            Name = "Gazebo Rafia Exahome",
                            Price = 430000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryTable")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryTable");
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProductTable")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "SaleTable")
                        .WithMany("SalesProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTable");

                    b.Navigation("SaleTable");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SalesProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
