// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomestico"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("3da6795d-4684-42ab-b1ac-059fb958bf28"),
                            Category = 1,
                            Description = "Lavarropa automatico Drean Next 6.06 Eco, 6kl, Blanco",
                            Discount = 20,
                            ImageUrl = "https://megatonedigital.vteximg.com.br/arquivos/ids/156425-520-520/135728_01.jpg?v=638265420231900000",
                            Name = "Lavarropa Drean",
                            Price = 740299m
                        },
                        new
                        {
                            ProductId = new Guid("9648780d-c63a-4847-981b-18f200e13765"),
                            Category = 1,
                            Description = "Microonda Daewoo, 23 Litros Bifunción D223dg",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/32/MKT0005BGH-1.jpg",
                            Name = "Microonda Daewoo ",
                            Price = 400846m
                        },
                        new
                        {
                            ProductId = new Guid("55121716-f5f8-4d48-8151-4353aab8be91"),
                            Category = 1,
                            Description = "Heladera Conqueror, 329L 2F-1600bda ",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/35/HEL1688CNQ.jpg",
                            Name = "Heladera Conqueror",
                            Price = 732299m
                        },
                        new
                        {
                            ProductId = new Guid("1a5bef09-74f0-4851-a257-025c739444e4"),
                            Category = 1,
                            Description = " Cocina Florencia 5518F Inoxidable Multigas Con 4 Hornallas",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/31/COC5518FLO.jpg",
                            Name = "Cocina Florencia",
                            Price = 519399m
                        },
                        new
                        {
                            ProductId = new Guid("08416f69-3583-4c90-928b-d0d455b2a500"),
                            Category = 2,
                            Description = "Celular Liberado A34 Gris 128 Gb, Ram 6 Gb, Octa Core",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/209/02/KIT3463SSG.jpg",
                            Name = "Celular Sansung A34",
                            Price = 695999m
                        },
                        new
                        {
                            ProductId = new Guid("61fa0f65-7500-44e2-90f1-29bb26c1ddef"),
                            Category = 2,
                            Description = "Notebook Cel Fire Glw2, Ram 4G, SSD 128 Gb, Pantalla 14",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/200/04/NOT2128PCB.jpg",
                            Name = "Notebook PCBOX",
                            Price = 499999m
                        },
                        new
                        {
                            ProductId = new Guid("77a0891a-35c8-44da-9165-4de892ff8937"),
                            Category = 2,
                            Description = "Joystick Robot Con Conexión Inalámbrica, Microsoft",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/235/JOY6910MIC.jpg",
                            Name = "Joystick Xbox",
                            Price = 129999m
                        },
                        new
                        {
                            ProductId = new Guid("51bd01f1-8688-4966-9241-06531ddaa399"),
                            Category = 2,
                            Description = "Tablet Wave 7 Dual I726a10, 2Gb, Ram 16Gb, Wifi",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/224/MKT0054EXO-1.jpg",
                            Name = "Tablet Wave 7 Exo",
                            Price = 134999m
                        },
                        new
                        {
                            ProductId = new Guid("95c6c15f-63c3-4ddf-b04e-ec324d47135e"),
                            Category = 3,
                            Description = "Reloj Inteligente, Negro, Bluetooth, Android, Notificaciones, Resistente al agua",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/239/MKT0034DXE.jpg",
                            Name = "Reloj Smartwatch Nt04",
                            Price = 33798m
                        },
                        new
                        {
                            ProductId = new Guid("498f3033-9878-4153-a597-23b2368aaa9f"),
                            Category = 3,
                            Description = "Anteojos de sol, Negro mate, lente gris ",
                            Discount = 0,
                            ImageUrl = "https://infinit.la/cdn/shop/products/6_f14d1e1f-e535-42e0-84ce-07c9f0aa93eb.jpg?v=1681141624&width=800",
                            Name = "Lentes de Sol Exclamation",
                            Price = 129000m
                        },
                        new
                        {
                            ProductId = new Guid("d28f55a7-13e5-4f4c-b91a-b769250b0f86"),
                            Category = 3,
                            Description = "Zapatillas de running, color negro, talle 44",
                            Discount = 0,
                            ImageUrl = "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/2881496d3d514a33905ef338f92dc37d_9366/zapatillas-de-running-adizero-sl.jpg",
                            Name = "Zapatillas Adizero Adidas",
                            Price = 171999m
                        },
                        new
                        {
                            ProductId = new Guid("940eb2e5-8520-401c-bf4f-55ebf9934848"),
                            Category = 3,
                            Description = "Riñonera Adicolor Classic",
                            Discount = 0,
                            ImageUrl = "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/5460d79ff58c46dcac93ae6701128b5e_9366/rinonera-adicolor-classic.jpg",
                            Name = "Riñonera Adicolor Adidas",
                            Price = 35999m
                        },
                        new
                        {
                            ProductId = new Guid("bf1eb3d3-b51f-4f47-b751-e0570c2bda4f"),
                            Category = 4,
                            Description = "Colchón 1 Plaza Resorte Bonnell Babel 0.80 X 1.90",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom/140/CHO7062IDL.jpg?version=35",
                            Name = "Colchón Bonnell Babel Inducol",
                            Price = 216999m
                        },
                        new
                        {
                            ProductId = new Guid("90a92d74-583f-4e31-9416-e937acdd6120"),
                            Category = 4,
                            Description = "Sillón De 3 Cuerpos, Esquinero,1.85Mts, Chenille Gris ",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/270/MKT0022AWO.jpg",
                            Name = "Sillón American Wood",
                            Price = 600000m
                        },
                        new
                        {
                            ProductId = new Guid("3c7699a0-35ca-48a8-8107-d30960f68170"),
                            Category = 4,
                            Description = "Divan Cama Pacifico, Madera, Ancho 90 Cm, largo 204 Cm",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/273/DIV0001INM.jpg",
                            Name = "Divan Inmacol",
                            Price = 259000m
                        },
                        new
                        {
                            ProductId = new Guid("a3fa73c6-c249-4c96-9f1e-dbce31d788e4"),
                            Category = 4,
                            Description = "Silla Comedor, Nórdica Eames, Diseño Moderno, Color Verde",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/339/MKT0250VIV.jpg",
                            Name = "Silla Comedor Vita Meet Makom",
                            Price = 179000m
                        },
                        new
                        {
                            ProductId = new Guid("aa4048d9-f5f3-42d2-b422-e1d312e428be"),
                            Category = 5,
                            Description = "Lavable Con Agua, Recargable, Color Negro",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom/76/AFE2724PHI.jpg?version=35",
                            Name = "Afeitadora Oneblade Qp2724, Philips",
                            Price = 52999m
                        },
                        new
                        {
                            ProductId = new Guid("ddc86d5a-5038-488d-bdea-4a4433e51cf8"),
                            Category = 5,
                            Description = "Uso En Humedo, No recargable, Potencia Total 2400 ",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/articulos/zoom2x/97/SEC0215GAM.jpg",
                            Name = "Secador De Pelo Eleganza Gama",
                            Price = 84800m
                        },
                        new
                        {
                            ProductId = new Guid("9d4e42fd-f6d2-4b1e-8a62-3debc0df7091"),
                            Category = 5,
                            Description = "Planchita de pelo, No recargable, Potencia Total 2400 ",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/97/PLA2118GAM.jpg",
                            Name = "Plancha Elegance Gamma",
                            Price = 101000m
                        },
                        new
                        {
                            ProductId = new Guid("a5397067-d82c-4e24-a6db-8ece92f37567"),
                            Category = 5,
                            Description = "Balanza Digital Vidrio Templado Hasta 150Kg",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/78/MKT0132PHO-1.jpg",
                            Name = "Balanza Digital Atma Ba7504n",
                            Price = 23400m
                        },
                        new
                        {
                            ProductId = new Guid("d9a4d325-e673-4ef9-898b-068588496974"),
                            Category = 6,
                            Description = "Con regulador, Visera, Color Azul",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/232/CAS0033SLP.jpg",
                            Name = "Casco Ciclismo Wt-032",
                            Price = 27600m
                        },
                        new
                        {
                            ProductId = new Guid("b02339db-3d36-4285-98d1-8ff2cfd82e04"),
                            Category = 6,
                            Description = "Rodado 29, Talle 18, Color Blanco",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/104/BIC2920NRD.jpg",
                            Name = "Bicicleta Mountain Bike Nordic",
                            Price = 320000m
                        },
                        new
                        {
                            ProductId = new Guid("1c51895e-a75e-483f-b206-6ac9dc201a60"),
                            Category = 6,
                            Description = "Velocidad 12 Km/h, Peso Máximo Soportado 100 kl",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/111/MKT0650ATR-1.jpg",
                            Name = "Cinta Caminadora Randers Arg-407",
                            Price = 716519m
                        },
                        new
                        {
                            ProductId = new Guid("eb35843e-5ea0-492b-876a-b8146ef60685"),
                            Category = 6,
                            Description = "Rodado 26, Con 7 Velocidades,Talle 18, Color Azul",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/104/MKT0379DNC-1.jpg",
                            Name = "Bicicleta De Paseo Lamborghini",
                            Price = 350490m
                        },
                        new
                        {
                            ProductId = new Guid("b50fa98f-2049-408c-a6c2-7b28701f7a81"),
                            Category = 7,
                            Description = "Con Lentejuelas Reversibles y Protecciones, Talle 36",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/257/MKT0104DNC.jpg",
                            Name = "Patines Lamborghini",
                            Price = 98020m
                        },
                        new
                        {
                            ProductId = new Guid("c9451962-9198-4963-9d18-de05a83d199e"),
                            Category = 7,
                            Description = "Silla de comer, Color rosa",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/119/MKT0203DNC.jpg",
                            Name = "Sillita De Comer Booster Lamborghini",
                            Price = 97860m
                        },
                        new
                        {
                            ProductId = new Guid("c738ba3b-18bb-4458-9347-81e09791c4e2"),
                            Category = 7,
                            Description = "Caminador musical con panel didactico",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/325/MKT0616ATR-1.jpg",
                            Name = "Caminador Musical Bebesit 1226",
                            Price = 52280m
                        },
                        new
                        {
                            ProductId = new Guid("43f39e14-00c8-489e-bee4-d2309f8860d3"),
                            Category = 7,
                            Description = "Moto a batería, Color azul y negro",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/362/MKT0032BBS-1.jpg",
                            Name = "Moto a batería Bmw K1300",
                            Price = 530000m
                        },
                        new
                        {
                            ProductId = new Guid("822873fa-3bd4-4493-96ab-f8987c7f5489"),
                            Category = 8,
                            Description = "Gaseosa 500 ml",
                            Discount = 0,
                            ImageUrl = "https://cdn.tiendanegocio.com/gallery/17745/img_17745_18b20896ea8.jpeg",
                            Name = "Coca Cola 500 ml",
                            Price = 750m
                        },
                        new
                        {
                            ProductId = new Guid("72ff9828-19d7-436d-94b1-cc26435e0c65"),
                            Category = 8,
                            Description = "Vino malbec 750 ml",
                            Discount = 0,
                            ImageUrl = "https://cdn.tiendanegocio.com/gallery/17745/img_17745_18b4b8c013b.jpeg",
                            Name = "Dv Catena Malbec",
                            Price = 15800m
                        },
                        new
                        {
                            ProductId = new Guid("1f5c9ba8-9b18-428f-8348-2000e62ec08f"),
                            Category = 8,
                            Description = "Cafe torrado, 170 GR",
                            Discount = 0,
                            ImageUrl = "https://cdn.tiendanegocio.com/gallery/17745/img_17745_18b1f7b2bf9.jpeg",
                            Name = "Cafe Dolca",
                            Price = 1900m
                        },
                        new
                        {
                            ProductId = new Guid("e1eb20b6-0f03-4e14-afad-062848f5ff36"),
                            Category = 8,
                            Description = "Ferrero x140g",
                            Discount = 0,
                            ImageUrl = "https://www.golomax.com.ar/uploads/centum/articles/home/7003428_1.jpg",
                            Name = "Nutella",
                            Price = 2565m
                        },
                        new
                        {
                            ProductId = new Guid("d996fb77-a8e1-4aff-99c8-c814eddba425"),
                            Category = 9,
                            Description = "Autor Dibu Martinez, Libro tapa blanda",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/2733557-thickbox_default/dibu-martinez-pasion-por-el-futbol.jpg",
                            Name = "Pasión por el fútbol",
                            Price = 12800m
                        },
                        new
                        {
                            ProductId = new Guid("65f3a6e1-7a4c-4c4d-a2cd-cb5effd0628b"),
                            Category = 9,
                            Description = "Autor Michael Crichton, Libro tipo bolsillo",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/3243614-thickbox_default/parque-jurasico-jurassic-park.jpg",
                            Name = "Parque Jurásico",
                            Price = 23500m
                        },
                        new
                        {
                            ProductId = new Guid("aa941147-5944-4569-bcda-d080af37e814"),
                            Category = 9,
                            Description = "Autor Rick Riordan, Libro tapa blanda",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/3477641-thickbox_default/la-torre-de-neron-las-pruebas-de-apolo-5.jpg",
                            Name = "La torre de Nerón, Las pruebas de Apolo 5",
                            Price = 29900m
                        },
                        new
                        {
                            ProductId = new Guid("8583e23b-2ed1-4630-a367-a20092fa637e"),
                            Category = 9,
                            Description = "Autor Ernest Cline, Libro tapa blanda",
                            Discount = 0,
                            ImageUrl = "https://www.penguinlibros.com/ar/3495318-thickbox_default/ready-player-two.jpg",
                            Name = "Ready player Two",
                            Price = 30800m
                        },
                        new
                        {
                            ProductId = new Guid("94013188-d7a9-4c89-987d-3768010a963d"),
                            Category = 10,
                            Description = "Material madera",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/343/MKT0425EMC-1.jpg",
                            Name = "Reposera para jardín EMC",
                            Price = 246800m
                        },
                        new
                        {
                            ProductId = new Guid("2ef8edfc-84db-475e-a969-aa9ace5ace0b"),
                            Category = 10,
                            Description = "Material madera",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/343/MKT0425EMC-1.jpg",
                            Name = "Reposera para jardín EMC",
                            Price = 246800m
                        },
                        new
                        {
                            ProductId = new Guid("4a404d8d-b936-421a-aace-789fdb56c766"),
                            Category = 10,
                            Description = "Parrilla portátil, plegable para camping",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/316/MKT0048IUR.jpg",
                            Name = "Parrilla portátil carbón balcon Mor Amazonas",
                            Price = 64900m
                        },
                        new
                        {
                            ProductId = new Guid("8eedd19a-6252-49c8-9de0-7a6c31531698"),
                            Category = 10,
                            Description = "Gazebo de 6X3, con puerta y ventanas, Color blanco",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/114/MKT0058RBJ.jpg",
                            Name = "Gazebo Rafia Exahome",
                            Price = 430000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal( 15, 2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 15, 2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryTable")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryTable");
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProductTable")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "SaleTable")
                        .WithMany("SalesProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTable");

                    b.Navigation("SaleTable");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SalesProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
